### PR TITLE
Check cookie within JS first before initializing form: bypasses WP ca…

### PR DESCRIPTION
**Pull request by matthisamoto**
_Check cookie within JS first before initializing form: bypasses WP caching issues_

This is probably not an ideal solution but I needed something today for a client whose Pantheon Cache plugin was causing problems. First suggestion would be to change the magic cookie name string. Tested on client site, it does work.

references issue #93

### CODE REVIEW

**Comment by alexstandiford** [comment]
Hey @matthisamoto - Correct me if I'm wrong, but it looks like you more-or-less did what I suggested in issue #93, is that right? You're saying that checking the cookie in the JS is resolving the issue?

**Comment by matthisamoto** [comment]
Yep did exactly what you suggested. And yeah it works. So basically, if it's drawing the script because of caching, this is an extra check, and if there is no caching, it just works as you'd intended and this doesn't really become an issue. There may be some unforeseen consequences as I'm not totally familiar with everything you've written here but the quick check did keep the form from appearing on every page despite having submitted the age.

**Comment by alexstandiford** [comment]
Sounds good. Thanks @matthisamoto - the confirmation that this resolved the issue definitely helps. I'm probably going to take it a step further and remove the popup logic from PHP altogether.

Thanks again for the PR!

**Comment by alexstandiford** [comment]
Thanks again! I'm **Finally** getting around to doing something with this PR

**Pull request merged**
